### ISSUE TITLE
unable to close menu after spawning buddy in 

### ISSUE THREAD

**Issue by rmtx83** [CarrionAndOn/LittleBuddy#1]
after i spawn in the buddy i am unable to go to bonemenu at all and when i try to close the menu again it stays stuck open causing me to have to restart the game

**Comment by FragileDeviations** [comment]
i've tested it and this never happened, are you on quest?

**Comment by rmtx83** [comment]
i am using pcvr

**Comment by FragileDeviations** [comment]
Can you give a log?

**Comment by FragileDeviations** [comment]
This was fixed in the latest commit.
